### ISSUE TITLE
Not working in Chrome 41

### ISSUE THREAD

**Issue by aethant** [FremyCompany/css-regions-polyfill#17] opened 2015-04-11 18:24 UTC
Not sure what's causing it, as it's failing silently when I follow the instructions here in the repo, but the polyfill no longer works. Inside, say, Codepen, the polyfill flows alright. However, "in the wild", there's no action, though it will throw errors when I livereload my CSS. For example:

  ```Parse error at token 21438: {. Attempt to open a curly-block in a statement-type at-rule.
   Parse error at token 29046: {. Attempt to open a curly-block in a statement-type at-rule.
   Parse error at token 30209: DELIM(*). undefined
   Parse error at token 30296: DELIM(*). undefined```

   All on line 1783 of cssregions.js, non-minifed.

With Modernizr in the mix, I get the following error:

   ```Uncaught Error: Please use the anHTMLElement.myStyle property to get polyfilled properties```
      on line 2843

  four times in a row in the console, which seems to point to the cssmask test in Modernizer.

The link from the Adobe blog (http://blogs.adobe.com/webplatform/2014/03/10/css-regions-polyfill-better-smarter-fuller/) to the National Geo demo (http://adobe-webplatform.github.io/Demo-for-National-Geographic-Orphan-Elephants/) leaves all the flow-into content at the bottom of the page, with the flow-from regions empty and in place.

**Comment by FremyCompany** [comment] 2015-04-13 16:55
Hi,

Thanks for reporting the error! I'll work on it when I've some free time to spend on this.

The second error isn't a huge problem, I would say. It just means that Modernizer will find out the support for the properties he looks for isn't complete, and it's totally fine. 

The first one is more annoying because it's a css parser error. I updated the parser library some time ago, but I'm not quite sure I propagated to css-regions-polyfill all the fixes that have been made since then to make this parser work properly. 

A possible solution would be to replace the src/core css files of this repo by the ones of the css-grid-polyfill which are more up-to-date and see if it makes any difference. That's something I could do in a very short time. I'll maybe get to this sometime today. If this isn't sufficient, then we've met yet another case where the parser fails and should be fixed, in which case I'll ping its author^_^

Best regards,
François

**Comment by aethant** [comment] 2015-04-13 20:08
Awesome. I'll keep an eye out. Thanks very much!

**Comment by FremyCompany** [comment] 2015-04-22 19:49
Sorry for the delay in keeping up with this. I noticed the css-regions-polyfill never was upgraded to the new polyfill infrastructure of css-grid-polyfill. This should be done, for sure, but it will take some time and I didn't have an opportunity to tackle this just yet. I hope to work on it this week-end.

**Comment by aethant** [comment] 2015-04-22 20:01
No rush. Thank you for checking in!

**Comment by FremyCompany** [comment] 2015-05-09 19:03
As far as I know, the v3.0 version I just shipped is working in Chrome again. Please tell me if you're facing any other issue due to the new version.

Best regards,
François

**Closed by FremyCompany** 2015-05-09 19:03 UTC
Labels: bug

**Comment by 1aurabrown** [comment] 2018-10-04 13:37
Hey I am trying to implement your polyfill, but I am experiencing this problem as well in Chrome. 

```
Parse error at token 0: DELIM(*).
undefined
```

This is the stack trace
![screen shot 2018-10-04 at 3 36 06 pm](https://user-images.githubusercontent.com/3171662/46477583-40034c00-c7eb-11e8-9671-fae4542f6c3f.png)

Any ideas?

**Comment by FremyCompany** [comment] 2018-10-04 17:54
Your css file seems to contain `*zoom: 1` which is not valid css (and probably a hack for IE), so I would expect a parse error to happen there. The real question is what the code does with this parse error, I would tend to believe it continue to parse or stop parsing entirely. It should continue to parse and this issue this parse error as a warning, but I haven't written that parser, it might not work properly, I am not sure. 

If you don't want that warning, you can update the css parser to ignore DelimToken with value "*" while parsing declaration lists.

**Comment by FremyCompany** [comment] 2018-10-04 17:55
Ok, I just took a look at the code, and I can confirm that this warning does not prevent the code from working properly as the function has proper error handling in place:

https://github.com/FremyCompany/css-regions-polyfill/blob/master/src/core/css-syntax.js#L1028

The `parseerror` function is only doing a console.log:

https://github.com/FremyCompany/css-regions-polyfill/blob/master/src/core/css-syntax.js#L946
