### ISSUE TITLE
Block elements don't partake in css regions content flow

### ISSUE THREAD

**Issue by FelixAkk** [FremyCompany/css-regions-polyfill#21] opened 2015-05-03 14:40 UTC
I did an experiment with the current master, and noticed that though the css regions polyfill works great for inline elements like paragraphs, but elements like `<div>` and `<h1>` seem to be ommitted. That's really too bad, because those are part of the content very often :)

Is this a configuration problem perhaps?

**Comment by metaljoe** [comment] 2015-05-05 09:44
I think I have the same problem. I have complex content (which includes a lot of divs) that I want to flow across several container divs - but only the first container is ever populated. The content doesn't flow into the subsequent containers.

**Comment by FremyCompany** [comment] 2015-05-05 17:08
I'm sorry to hear about this. I'm really lagging on my css-regions-polyfill backlog, but I'll do my best to fix this ASAP. Could you please provide a public repro, to speed bump my dev process once I get some free time to spend on it?

Thank you for reaching me,
François

**Comment by FremyCompany** [comment] 2015-05-09 18:43
Please note I just made the upgrade to the new version of the polyfill.
It would help me if you could check if the problem is solved for your specific case.

Best regards,
François

**Comment by FremyCompany** [comment] 2015-05-09 19:03
(I'm closing this for now, and will reopen based on evidences showing it still doesn't work for you)

**Closed by FremyCompany** 2015-05-09 19:03 UTC

**Comment by metaljoe** [comment] 2015-05-11 07:49
Cheers for looking at this so quickly - the latest code works fine for my particular case. Hopefully it fixes it for FelixAkk too!

**Comment by metaljoe** [comment] 2015-05-12 07:41
Hmm, on further examination it might not be flowing properly with wkhtmltopdf 0.12. I'm using it to generate brochures in both HTML (for previews) and PDF format (for the downloadable brochure).

I'll hopefully find time today to do some further investigation and will get back to you. If the problem isn't down to wkhtmltopdf, or a PEBKAC one, I'll produce a minimal test case.

**Comment by metaljoe** [comment] 2015-05-12 10:31
It looks to be the call to requestAnimationFrame in cssRegions.Flow.prototype.relayout - the function passed is never executed, and thus _relayout is never called. This seems to be an issue with wkhtmltopdf, probably because it's headless.

**Comment by FremyCompany** [comment] 2015-05-12 16:24
Feel free to try to execute "window.requestAnimationFrame = function(f) { return setTimeout(f, 16); }" before my polyfill runs. If it turns out it solves the problem, then you're a lucky person :-)

**Comment by FremyCompany** [comment] 2015-05-12 16:26
Otherwise, you may simply disable the rAF throttling because you don't care about not damaging the fps in a headless browser. It's probably fine to change the task scheduler to run all tasks directly and not break down when it exceeds some threshold.

**Comment by FelixAkk** [comment] 2015-05-13 15:16
Works like a charm! Many thanks for fixing this so quickly! :)

**Comment by FelixAkk** [comment] 2015-05-13 15:55
Just to give an idea what I used it for: https://cloud.aerix.nl/index.php/apps/files_sharing/ajax/publicpreview.php?x=3840&y=2188&a=true&file=Screen%2520Shot%25202015-05-13%2520at%252017.38.41.png&t=8p1EaF1RgthveaU&scalingup=0

**Comment by FremyCompany** [comment] 2015-05-13 21:26
You're welcome. I'm glad to see this project used by creative people around the world :-)
